"""Image column to Images

Revision ID: 504ff6f9e299
Revises: d7b0ca14e644
Create Date: 2025-09-15 16:06:53.401797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504ff6f9e299'
down_revision: Union[str, Sequence[str], None] = 'd7b0ca14e644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('projects', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'images')
    # ### end Alembic commands ###
