"""rename file to image

Revision ID: 62b4b243b517
Revises: 504ff6f9e299
Create Date: 2025-09-18 12:29:43.688491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b4b243b517'
down_revision: Union[str, Sequence[str], None] = '504ff6f9e299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('tickets', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'image')
    # ### end Alembic commands ###
